### ISSUE TITLE
version not compatible error

### ISSUE THREAD

**Issue by SnowWindSaveYou** [IvanMurzak/Unity-EntityFrameworkCore.3.1.25#1]
![image](https://user-images.githubusercontent.com/31602852/199384784-2abd98d4-79ad-42cb-af35-c1425e542153.png)

**Comment by IvanMurzak** [comment]
@SnowWindSaveYou be sure that your Unity project has .NET STANDARD 2.0. Because EntityFramework 3.1.X doesn't support .NET 4.x
![image](https://user-images.githubusercontent.com/9135028/199503184-dae8ebdb-6eaf-490d-81f9-687f24a85beb.png)

![image](https://user-images.githubusercontent.com/9135028/199503568-f96b666c-fa20-48aa-aaba-287dd0f73b0c.png)
